<!-- Page Content -->
<div class="container">
    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3 text-center">E-ROD by Prevrod</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item w-100 text-center">
            Registo de atividades de condução
        </li>
    </ol>
    <div class="alert alert-danger py-2 mb-1 text-center">
        <i class="fas fa-exclamation-triangle pe-2"></i><span class="fw-bold">VERSÃO DEMO</span><i class="fas fa-exclamation-triangle ps-2"></i>
    </div>
</div>
<?php
include $core_elements->tree_struct()->templatedir->publicblock . "/publiclogin.php";
?>