<?php
$pubuser_data = $public_data->get_pubuser_data($id,$companyid);
$modalvis = "";
$company_name = $public_data->get_company_name($pubuser_data[1]);
$contract_ini = date("d/m/Y",strtotime($pubuser_data[13]));
$date_exp = date("d/m/Y",strtotime($pubuser_data[14]));
$date_create = date("d/m/Y H:i:s",strtotime($pubuser_data[17]));
$last_update = date("d/m/Y H:i:s",strtotime($pubuser_data[18]));
$seg_arr = explode("|",$pubuser_data[12]); $seg_arr_json = str_replace("\"","",json_encode($seg_arr));
$main_seg = $public_data->get_segment_data($seg_arr[0]);
$curr_seg_array = $public_data->get_segment_array($seg_arr);
$entity_segment_list = $public_lists->entity_segment_list($pubuser_data[1]);
$status_desc = array("Suspenso","Ativo");
if (!is_null($pubuser_data[19])) {
    $status = $pubuser_data[19];
} else {
    $status = 0;
}
$opunits_list = $public_lists->entityopus_select_list($pubuser_data[1]);
$usertype_list = $public_lists->pubusertype_list();
$subsctype_list = $public_lists->pubusersubsc_type_list();
$subsstatus_list = $public_lists->pubusersubsc_status_list();
$formcssid = "pubuser-update-form";
$entity_data = $public_data->get_entity_data($pubuser_data[1]);
?>
<div id="infoBoard" class="carousel slide carousel-fade" data-bs-touch="false" data-bs-interval="false">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="container-fluid mb-3">
                <div class="card">
                    <div class="card-header text-white bg-success">
                        <?php echo "$pubuser_data[4] ($pubuser_data[0])"; ?><a class="btn text-white px-1 py-0 ms-3" data-bs-target="#infoBoard" data-bs-slide="next"><i class="far fa-edit"></i></a>
                    </div>
                    <div class="card-body pb-1">
                        <div class="row pt-0">
                            <div class="col-md-2 pt-3 mb-1 bg-light border-top border-4 border-success">
                                <label class="fw-bold">Utilizador / trabalhador:</label>    
                                <span class="d-block lh-1 pb-2"><h5 class="text-success"><?php echo $pubuser_data[4]; ?></h5></span>
                                <label class="fw-bold">NIF:</label>  
                                <span class="d-block lh-1 pb-2"><h5 class="text-success"><?php echo $pubuser_data[10]; ?></h5></span>
                                <label class="fw-bold">Empresa:</label>  
                                <span class="d-block lh-1 pb-2"><a class="fw-bold text-primart text-decoration-none" href="/public/company"><?php echo $company_name; ?></a></span>
                            </div>
                            <div class="col-md-2 pt-3 mb-1 border-top border-4 border-success">
                                <label class="fw-bold">Morada:</label>  
                                <span class="d-block lh-1 pb-2"><?php echo $pubuser_data[5]; ?></span>
                                <label class="fw-bold">CP / Localidade:</label>  
                                <span class="d-block lh-1 pb-2">
                                <?php 
                                echo (strlen($pubuser_data[6]) > 0) ? $pubuser_data[6] : "";
                                echo (strlen($pubuser_data[6]) > 0 && strlen($pubuser_data[7]) > 0) ? " " : "";
                                echo (strlen($pubuser_data[7]) > 0) ? $pubuser_data[7] : "";
                                ?>        
                                </span>
                                <label class="fw-bold">Unidade operacional:</label>  
                                <span class="d-block lh-1 pb-2">
                                <?php
                                if ($pubuser_data[2] == 0) {
                                    echo "Sede";
                                }
                                foreach ($opunits_list as $opunits_item) {
                                    if ($opunits_item[0] == $pubuser_data[2]) {
                                        echo $opunits_item[1];
                                    }
                                }
                                ?>
                                </span>        
                            </div>
                            <div class="col-md-2 pt-3 mb-1 bg-light border-top border-4 border-success">
                                <label class="fw-bold">e-mail:</label>  
                                <span class="d-block lh-1 pb-2"><?php echo $pubuser_data[8]; ?></span>
                                <label class="fw-bold">Telefone:</label>  
                                <span class="d-block lh-1 pb-2"><?php echo $pubuser_data[9]; ?></span>
                            </div>
                            <div class="col-md-2 pt-3 mb-1 border-top border-4 border-info">
                                <label class="fw-bold">Tipo de utilizador:</label>
                                <span class="d-block lh-1 pb-2">
                                <?php
                                foreach ($usertype_list as $usertype_item) {
                                    if ($usertype_item[0] == $pubuser_data[3]) {
                                        echo $usertype_item[1];
                                    }
                                }
                                ?>
                                </span>
                                <label class="fw-bold">Carta de condução:</label> 
                                <span class="d-block lh-1 pb-2"><?php echo strlen($pubuser_data[11] > 0) ? $pubuser_data[11] : "N/A" ?></span>
                                <label class="fw-bold">Segmentos:</label> 
                                <span class="d-block lh-1 pb-2">
                                <?php
                                foreach ($curr_seg_array as $curr_seg_item) {
                                    echo $curr_seg_item . "<br>";
                                }
                                ?>
                                </span>
                            </div>
                            <div class="col-md-2 pt-3 mb-1 bg-light bg-light border-top border-4 border-warning">
                                <label class="fw-bold">Início de contrato:</label>    
                                <span class="d-block lh-1 pb-2"><?php echo $contract_ini; ?></span>
                                <label class="fw-bold">Data de expiração:</label>    
                                <span class="d-block lh-1 pb-2"><?php echo $date_exp; ?></span>
                                <label class="fw-bold">Tipo de subscrição:</label>
                                <span class="d-block lh-1 pb-2">
                                <?php
                                foreach ($subsctype_list  as $subsctype_item) {
                                    if ($subsctype_item[0] == $pubuser_data[15]) {
                                        echo $subsctype_item[1];
                                    }
                                }
                                ?>
                                </span>
                                <label class="fw-bold">Estado da subscrição:</label>    
                                <span class="d-block lh-1 pb-2">
                                <?php
                                foreach ($subsstatus_list as $subsstatus_item) {
                                    if ($subsstatus_item[0] == $pubuser_data[16]) {
                                        echo $subsstatus_item[1];
                                    }
                                }
                                ?>  
                                </span>    
                            </div>
                            <div class="col-md-2 pt-3 mb-1 border-top border-4 border-warning">
                                <label class="fw-bold">Data de criação:</label>    
                                <span class="d-block lh-1 pb-2"><?php echo $date_create; ?></span>
                                <label class="fw-bold">Última atualização:</label>    
                                <span class="d-block lh-1 pb-2"><?php echo $last_update; ?></span>
                                <label class="fw-bold">Estado funcional:</label>    
                                <span class="d-block lh-1 pb-2"><?php echo $status_desc[$status]; ?></span>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="container-fluid mb-3">
                <div class="card">
                    <div class="card-header text-white bg-success">
                        <?php echo "$pubuser_data[4] ($pubuser_data[0])"; ?><a class="btn text-white px-1 py-0 ms-3" data-bs-target="#infoBoard" data-bs-slide="prev"><i class="fas fa-info-circle"></i></a>
                    </div>
                    <div class="card-body">
                        
                        <form id="<?php echo $formcssid; ?>" action="pubadminpubusers.php" class="needs-validation refresh-on-success" callbackurl="/public/publicusers" novalidate>
                        <fieldset<?php echo (is_null($pubuser_data[0])) ? " disabled" : ""; ?>>
                            <input type="hidden" name="itemid" id="itemid" value="<?php echo $pubuser_data[0]; ?>">
                            <input type="hidden" name="userid" id="userid" value="<?php echo $puser; ?>">
                            <input type="hidden" name="formaction" id="formaction" value="update">
                            
                            <input type="hidden" name="entityid" id="entityid" value="<?php echo $pubuser_data[1]; ?>">
                            <input type="hidden" name="segment" id="segment" value="<?php echo $seg_arr_json; ?>">

                            <input type="hidden" name="taxid" id="taxid" value="<?php echo $pubuser_data[10]; ?>">
                            <input type="hidden" name="subsctype" id="subsctype" value="<?php echo $pubuser_data[15]; ?>">
                            <input type="hidden" name="subscstatus" id="subscstatus" value="<?php echo $pubuser_data[16]; ?>">
                            <input type="hidden" name="expdate" id="expdate" value="<?php echo $date_exp; ?>">
                          
                            <div class="row">
                                <div class="col-md-7 mb-2">
                                    <div class="form-group">
                                        <label for="name">Nome</label>    
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Nome" value="<?php echo $pubuser_data[4]; ?>">
                                        <div id="name_warn" class="invalid-feedback"></div>
                                    </div>
                                </div>
                                <div class="col-md-2 mb-2">
                                    <div class="form-group">
                                        <label>NIF</label>  
                                        <input type="text" class="form-control" value="<?php echo $pubuser_data[10]; ?>" disabled>
                                    </div>
                                </div>
                                <div class="col-md-3 mb-2">
                                    <div class="form-group">
                                        <label for="type">Tipo de utilizador</label>
                                        <select class="form-control" name="type" id="type">
                                            <?php
                                            foreach ($usertype_list as $usertype_item) {
                                                if ($pubuser_data[3] == 1 && $usertype_item[0] <> 1) {
                                                    $optstatus = " disabled" ;
                                                } elseif ($pubuser_data[3] > 1 && $usertype_item[0] == 1) {
                                                    $optstatus = " disabled" ;
                                                } else {
                                                    $optstatus = "";
                                                }
                                            ?>
                                            <option value="<?php echo $usertype_item[0]; ?>"<?php echo ($usertype_item[0] == $pubuser_data[3]) ? " selected" : ""; echo $optstatus; ?>>
                                                <?php echo $usertype_item[1]; ?>
                                            </option>
                                            <?php } ?>
                                        </select>
                                        <div id="type_warn" class="invalid-feedback"></div>
                                    </div>    
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-7 mb-2">
                                    <div class="form-group">
                                        <label for="address">Morada</label> 
                                        <input type="text" class="form-control" id="address" name="address" placeholder="Morada" value="<?php echo $pubuser_data[5]; ?>">
                                        <div id="address_warn" class="invalid-feedback"></div>
                                    </div>
                                </div>
                                <div class="col-md-2 mb-2">
                                    <div class="form-group">
                                        <label for="zipcode">Código postal</label>  
                                        <input type="text" class="form-control" id="zipcode" name="zipcode" placeholder="xxxx-yyy" value="<?php echo $pubuser_data[6]; ?>">
                                        <div id="zipcode_warn" class="invalid-feedback"></div>
                                    </div>
                                </div>
                                <div class="col-md-3 mb-2">
                                    <div class="form-group">
                                        <label for="ziploc">Localidade</label>  
                                        <input type="text" class="form-control" id="ziploc" name="ziploc" placeholder="Localidade" value="<?php echo $pubuser_data[7]; ?>">
                                        <div id="ziploc_warn" class="invalid-feedback"></div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-7 mb-2">
                                    <div class="form-group">
                                        <label for="email">e-mail</label>  
                                        <input type="text" class="form-control" id="email" name="email" placeholder="x@yyy.com" value="<?php echo $pubuser_data[8]; ?>">
                                        <div id="email_warn" class="invalid-feedback"></div>
                                    </div>
                                </div>
                                <div class="col-md-2 mb-2">
                                    <div class="form-group">
                                        <label for="tel">Telefone</label>  
                                        <input type="text" class="form-control" id="tel" name="tel" placeholder="Telefone" value="<?php echo $pubuser_data[9]; ?>">
                                        <div id="tel_warn" class="invalid-feedback"></div>
                                    </div>
                                </div>
                                <div class="col-md-3 mb-2">
                                    <div class="form-group">
                                        <label for="opunit">Unidade operacional</label>
                                        <select class="form-control" name="opunit" id="opunit">
                                            <option value="0">Sede</option>
                                            <?php
                                            foreach ($opunits_list as $opunits_item) {
                                            ?>
                                            <option value="<?php echo $opunits_item[0]; ?>"<?php echo ($opunits_item[0] == $pubuser_data[2]) ? " selected" : "" ?>>
                                                <?php echo $opunits_item[1]; ?>
                                            </option>
                                            <?php } ?>
                                        </select>
                                        <div id="opunit_warn" class="invalid-feedback"></div>
                                    </div>  
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-2 mb-2">
                                    <div class="form-group">
                                        <label for="driverlic">Carta de condução</label>
                                        <input type="text" class="form-control" id="driverlic" name="driverlic" placeholder="Mº carta de condução" value="<?php echo $pubuser_data[11] ; ?>">
                                        <div id="driverlic_warn" class="invalid-feedback"></div>
                                    </div>
                                </div>
                                <div class="col-md-2 mb-2">
                                    <div class="form-group">
                                        <label for="contractini">Início de contrato</label>
                                        <input type="text" class="form-control" id="contractini" name="contractini" placeholder="dd/mm/aaaa" value="<?php echo $contract_ini; ?>">
                                        <div id="contractini_warn" class="invalid-feedback"></div>            
                                    </div>
                                </div>
                                <div class="col-md-2 mb-2">
                                    <div class="form-group">
                                        <label>Tipo de subscrição</label>
                                        <select class="form-control" disabled>
                                            <?php
                                            foreach ($subsctype_list  as $subsctype_item) {
                                            ?>
                                            <option value="<?php echo $subsctype_item[0]; ?>"<?php echo ($subsctype_item[0] == $pubuser_data[15]) ? " selected" : "" ?>>
                                                <?php echo $subsctype_item[1]; ?>
                                            </option>
                                            <?php } ?>
                                        </select>
                                     </div>
                                </div>
                                <div class="col-md-2 mb-2">
                                    <div class="form-group">
                                        <label>Estado da subscrição</label>
                                        <select class="form-control" disabled>
                                            <?php
                                            foreach ($subsstatus_list as $subsstatus_item) {
                                            ?>
                                            <option value="<?php echo $subsstatus_item[0]; ?>"<?php echo ($subsstatus_item[0] == $pubuser_data[16]) ? " selected" : "" ?>>
                                                <?php echo $subsstatus_item[1]; ?>
                                            </option>
                                            <?php } ?>
                                        </select>
                                     </div>
                                </div>
                                <div class="col-md-2 mb-2">
                                    <div class="form-group">
                                        <label>Segmento (principal)</label>
                                        <div class="input-group">
                                            <input type="text" class="form-control" id="mainsegment" value="<?php echo $main_seg; ?>" disabled>
                                            <div class="input-group-text">
                                                <a class="text-dark" data-bs-toggle="modal" data-bs-target="#segModal"><i class="far fa-list-alt"></i></a>
                                            </div>
                                            <div id="mainsegment_warn" class="invalid-feedback"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-2 mb-2">
                                    <div class="form-group">
                                        <label for="puserpwd">Password</label>
                                        <div class="input-group">
                                            <input type="password" class="form-control" id="puserpwd" name="puserpwd" placeholder="Password" value="KeepPassword" autocomplete="off">
                                            <div class="input-group-text">
                                                <a class="text-dark" data-bs-toggle="shpassword" data-bs-target="#puserpwd"><i class="fas fa-eye"></i></a>
                                            </div>
                                            <div id="puserpwd_warn" class="invalid-feedback"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-2 mb-2">
                                    <div class="form-group">
                                        <label for="status">Estado funcional</label>
                                        <select class="form-control bg-warning" name="status" id="status">
                                            <option class="bg-light" value="1"<?php echo ($status == "1") ? " selected" : "" ?>>Ativo</option>
                                            <option class="bg-light" value="0"<?php echo ($status == "0") ? " selected" : "" ?>>Suspenso</option>
                                        </select>
                                        <div id="status_warn" class="invalid-feedback"></div>
                                    </div>  
                                </div>
                                <div class="col-md-2 mb-2">
                                    <div class="form-group">
                                        <label>Data de expiralão</label>
                                        <input type="text" class="form-control" id="expdate" name="expdate" placeholder="dd/mm/aaaa" value="<?php echo $date_exp; ?>" disabled>
                                     </div>
                                </div>
                                <div class="col-md-2 mb-2">
                                  <div class="form-group">
                                      <label>Data de criação</label>
                                      <input type="text" class="form-control" value="<?php echo $date_create; ?>" disabled>
                                    </div>
                                </div>
                                <div class="col-md-2 mb-2">
                                    <div class="form-group">
                                        <label>Última atualização</label>
                                        <input type="text" class="form-control" value="<?php echo $last_update; ?>" disabled>
                                    </div>
                                </div>
                                <div class="col-md-<?php echo ($puser <> $id) ? "2" : "3" ; ?> mb-2"><!-- empty --></div>
                                <div class="col-md-1 mb-2">
                                    <button type="button" class="btn btn-success w-100 mt-3 pt-2 pb-2 text-nowrap" btnaction="form-send"><i class="fas fa-sync-alt"></i></button>
                                </div>
                                <?php if ($puser <> $id) { ?>
                                <div class="col-md-1 mb-2">
                                    <button type="button" class="btn btn-danger w-100 mt-3 pt-2 pb-2 text-nowrap" btnaction="form-delete"><i class="far fa-trash-alt"></i></button>
                                </div>
                                <?php } ?>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="alert alert-secondary text-secondary mt-3 d-none" id="form_status"></div>
                                </div>
                            </div>
                        </fieldset>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="js-companydata" class="d-none">
    <input type="hidden" id="js-entityname" value="<?php echo $entity_data[3]; ?>">
    <input type="hidden" id="js-entitytaxid" value="<?php echo $entity_data[4]; ?>">
    <input type="hidden" id="js-entityaddress" value="<?php echo $entity_data[5]; ?>">
    <input type="hidden" id="js-entityzipcode" value="<?php echo $entity_data[6]; ?>">
    <input type="hidden" id="js-entityziploc" value="<?php echo $entity_data[7]; ?>">
    <input type="hidden" id="js-entityemail" value="<?php echo $entity_data[8]; ?>">
    <input type="hidden" id="js-entitytel" value="<?php echo $entity_data[9]; ?>">    
</div>

<!-- Segment Modal -->
<?php
$modalid = "segModal";
$modaltit = "Segmentos";
$editstatus = $modalvis;
$cbxsetid = $formcssid . "-seg";
$trgfield = "segment";
$modal_list = $entity_segment_list;
$cbxc_arr = $seg_arr;
$curr_modal_list = $curr_seg_array;
if (!is_null($pubuser_data[0])) { 
    include $core_elements->tree_struct()->templatedir->publicblock . "/cbxmodal.phtml";
}
?>

<?php if (!is_null($pubuser_data[0]) && $pubuser_data[3] > 1) { ?>
<div class="container-fluid mt-1">
    <div class="row">
        <div class="col-6 text-start">
            <a class="btn" data-bs-target="#bottomBoard" data-bs-slide="prev"><i class="fas fa-chevron-left fs-2x text-success"></i><i class="fas fa-chevron-left fs-2x text-success"></i></a>
        </div>
        <div class="col-6 text-end">
            <a class="btn" data-bs-target="#bottomBoard" data-bs-slide="next"><i class="fas fa-chevron-right fs-2x text-success"></i><i class="fas fa-chevron-right fs-2x text-success"></i></a>
        </div>
    </div>
</div>
<div id="bottomBoard" class="carousel slide" data-bs-touch="false" data-bs-interval="false">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="container-fluid">
                <div class="card h-100">
                    <div class="card-header text-dark bg-light">
                        Atividades do utilizador / trabalhador
                    </div>
                    <div class="card-body">
                        <?php include $core_elements->tree_struct()->templatedir->publicblock . "/pubuseractivities.phtml"; ?>
                    </div>   
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="container-fluid">
                <div class="card h-100">
                    <div class="card-header text-dark bg-light">
                        Anãlise temporal de atividades de  utilizador / trabalhador
                    </div>
                    <div class="card-body">
                        <?php // include $core_elements->tree_struct()->templatedir->adminblock . "/pubuseractivities.phtml"; ?>
                    </div>   
                </div>
            </div>
        </div>
    </div>
</div>
<?php } ?>
