<?php
$nut_list = $admin_lists->nut_list();
$zone_list = $admin_lists->zone_list($nutflt);
$segment_list = $admin_lists->segment_list($groupid);
$etype_list = $admin_lists->etype_list();
?>
<div class="container-fluid mb-2">
    <div class="card">
        <div class="card-header text-white bg-secondary">
            Filtros
        </div>
        <div class="card-body">
            <form action="entities" name="entities" id ="entities">
                <input type="hidden" id = "offset" name="offset" value="<?php echo $offset;?>">
                <input type="hidden" id = "limit" name="limit" value="<?php echo $limit;?>">
                <input type="hidden" id = "sortfld" name="sortfld" value="<?php echo $sortfld;?>"> 
                <div class="row">
                    <div class="col-md-4">
                        <div class="row">
                            <div class="col-lg px-1">
                                <label class="sr-only" for="entity">Entidade</label>
                                <input type="text" class="form-control form-control-sm mb-2 list-filter" name="entity" id="entity" placeholder="Entidade" value="<?php echo $entityflt; ?>">
                            </div>
                            <div class="col-lg px-1">
                                <label class="sr-only" for="nut">Região</label>
                                <div class="input-group mb-2">
                                    <div class="input-group-text"><i class="fas fa-globe-americas"></i></div>
                                    <select class="form-control form-control-sm list-filter" name="nut" id="nut">
                                        <option value="">-- Região --</option>
                                        <option value="0"<?php echo ($nutflt == "0") ? " selected" : "" ?>>Todas as regiões</option>
                                        <option value="1"<?php echo ($nutflt == "1") ? " selected" : "" ?>>Não definida</option>
                                        <?php
                                        foreach ($nut_list as $nut_item) {
                                        ?>
                                            <option value="<?php echo $nut_item[0]; ?>"<?php echo ($nut_item[0] == $nutflt) ? " selected" : "" ?>><?php echo $nut_item[1]; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="row">
                            <div class="col-lg px-1">
                                <label class="sr-only" for="zone">Concelho</label>
                                <div class="input-group mb-2">
                                    <div class="input-group-text"><i class="fas fa-map-marker-alt"></i></div>
                                    <select class="form-control form-control-sm list-filter" name="zone" id="zone">
                                        <option value="">-- Concelho ou país --</option>
                                        <option value="0"<?php echo ($zoneflt == "0") ? " selected" : "" ?>>Todos os concelhos e países</option>
                                        <?php
                                        if ($nutflt == "0" || $nutflt == "1") {
                                        ?>
                                        <option value="1"<?php echo ($zoneflt == "1") ? " selected" : "" ?>>Não definido</option>
                                        <?php } ?>
                                        <?php
                                        foreach ($zone_list as $zone_item) {
                                        ?>
                                            <option value="<?php echo $zone_item[0]; ?>"<?php echo ($zone_item[0] == $zoneflt) ? " selected" : "" ?>><?php echo $zone_item[1]; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg px-1">
                                <label class="sr-only" for="segment">Segmento</label>
                                <div class="input-group mb-2">
                                    <div class="input-group-text"><i class="fas fa-tag"></i></div>
                                    <select class="form-control form-control-sm list-filter" name="segment" id="segment">
                                        <option value="">-- Segmento --</option>
                                        <option value="0"<?php echo ($segmentflt == "0") ? " selected" : "" ?>>Todos os segmentos</option>
                                        <?php
                                        foreach ($segment_list as $segment_item) {
                                        ?>
                                            <option value="<?php echo $segment_item[0]; ?>"<?php echo ($segment_item[0] == $segmentflt) ? " selected" : "" ?>><?php echo $segment_item[1]; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="row">    
                            <div class="col-lg px-1">
                                <label class="sr-only" for=etype>Tipo de entidade</label>
                                <div class="input-group mb-2">
                                    <div class="input-group-text"><i class="fas fa-user-tag"></i></div>
                                    <select class="form-control form-control-sm list-filter" name="etype" id="etype">
                                        <option value="">-- Tipo de entidade --</option>
                                        <option value="-1"<?php echo ($etypeflt == "-1") ? " selected" : "" ?>>Todos os tipos</option>
                                        <option value="0"<?php echo ($etypeflt == "0") ? " selected" : "" ?>>Em avaliação</option>
                                        <?php
                                        foreach ($etype_list as $etype_item) {
                                        ?>
                                            <option value="<?php echo $etype_item[0]; ?>"<?php echo ($etype_item[0] == $etypeflt) ? " selected" : "" ?>><?php echo $etype_item[1]; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg px-1 text-end"><input type="button" class="btn btn-sm btn-danger list-filter-clear" value="Limpar"></div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>