<div class="row">
	<div class="col-md-12">
		<nav aria-label="Page navigation">
		  	<ul class="pagination" form="<?php echo $formref; ?>">
		    	<li class="page-item" data-offset="<?php echo $ofi; ?>">
		      		<a class="page-link" href="#" aria-label="Início">
		        		<span aria-hidden="true">&laquo;</span>
		        		<span class="sr-only">Previous</span>
		      		</a>
		    	</li>
		    	<li class="page-item<?php echo ($cur_pg == $pg1) ? " active" : ""; ?>" data-offset="<?php echo $of1; ?>"><a class="page-link" href="#"><?php echo $pg1; ?></a></li>
		    	<?php if ($tot_pgs > 1) { ?> 	
		    		<li class="page-item<?php echo ($cur_pg == $pg2) ? " active" : ""; ?>" data-offset="<?php echo $of2; ?>"><a class="page-link" href="#"><?php echo $pg2; ?></a></li>
		    	<?php } ?>
		    	<?php if ($tot_pgs > 2) { ?>
		    		<li class="page-item<?php echo ($cur_pg == $pg3) ? " active" : ""; ?>" data-offset="<?php echo $of3; ?>"><a class="page-link" href="#"><?php echo $pg3; ?></a></li>
		    	<?php } ?>
		    	<li class="page-item" data-offset="<?php echo $ofl; ?>">
		      		<a class="page-link" href="#" aria-label="Fim">
		        		<span aria-hidden="true">&raquo;</span>
		        		<span class="sr-only">Next</span>
		      		</a>
		    	</li>
		  	</ul>
		</nav>
	</div>
</div>