<!-- Navigation -->
<nav id="topelm" class="navbar fixed-top navbar-light py-1" style="background-color: rgba(230,230,230,0.85)">
    <div class="container align-items-start">
        <!--a class="navbar-brand" href="index.php?pg=home"-->
            <img src="<?php echo $fe_img_path; ?>/top_navbar_logo.png" style="height:35px">
        <!--/a-->
        <div class="align-self-center pt-1 text-secondary">
            <a class="text-primary" id="fullsw"><i class="fa-solid fa-expand fa-2x me-2"></i>
            <a class="text-danger" id="logout"><i class="fas fa-sign-out-alt fa-2x"></i></a>
        </div>
    </div>
</nav>