<!-- Navigation -->
<nav id="topelm" class="navbar fixed-top navbar-expand-lg navbar-light py-3" style="background-color: rgba(230,230,230,0.85)">
    <div class="container align-items-start">
        <a class="navbar-brand" href="index.php?pg=home">
            <img src="<?php echo $fe_img_path; ?>/top_navbar_logo.png">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse mt-1 justify-content-end" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link fw-bold" href="index.php?pg=home">Aplicação</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fw-bold" href="index.php?pg=help">Ajuda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fw-bold" href="index.php?pg=contacts">Contactos</a>
                </li>
                <?php if ($puser > 0) { ?>
                <li class="nav-item dropdown">
                    <a class="nav-link fw-bold" href="#" id="navbarDropdownuser" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i></a>
                    <div class="dropdown-menu dropdown-menu-end p-3"style="background-color: rgba(230,230,230,0.9)" aria-labelledby="navbarDropdownuser" data-bs-popper="none">
                        <?php echo "Utilizador $puser"; ?>
                        <a class="simple-link" style="font-size: 0.8rem" href="/index.php?role=public&pg=logout">Terminar sessão</a>
                    </div>
                </li>
                <?php } ?>
            </ul>
        </div>
    </div>
</nav>