<div class="container-fluid mt-2">
    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-danger py-2 mb-1 text-center">
                <i class="fas fa-exclamation-triangle pe-2"></i><span class="fw-bold">VERSÃO DE DEMONSTRAÇÃO E FORMAÇÃO</span><i class="fas fa-exclamation-triangle ps-2"></i>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
        	<div class="alert alert-success py-2 mb-2">
  				<?php include $core_elements->tree_struct()->templatedir->publicblock . "/activesession.phtml"; ?>
			</div>
        </div>
    </div>
</div>
